# Generated by Django 4.0.3 on 2023-06-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='boards/images/%Y/%m/%d/'),
        ),
    ]
