# Generated by Django 4.0.3 on 2023-06-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_question_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='boards/files/%Y/%m/%d/'),
        ),
    ]
