# Generated by Django 4.0.3 on 2023-06-20 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0008_category_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voter',
            field=models.ManyToManyField(blank=True, null=True, related_name='voter_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
